name: "Join YAML Files"
description: "An action to join yaml files together"
author: "Timm Hirsens"

inputs:
  input-glob:
    required: true
    description: "the glob of files to join together"
outputs:
  file:
    description: "the joined file"

runs:
  using: "node12"
  main: "dist/index.js"
